from app.core.database import Base
from app.models.ai_analysis import (
    AIAnalysis,
    AIAnalysisStatus,
    AIAnalysisType,
    AnomalyDetection,
)
from app.models.audit import AuditAction, AuditLog
from app.models.base import TenantMixin, TimestampMixin

# Phase 3: Full Compliance Platform Models
from app.models.compliance import (
    AlertSeverity,
    AlertStatus,
    Assessment,
    AssessmentResult,
    AssessmentStatus,
    AssignmentStatus,
    # Audits
    Audit,
    AuditFinding,
    AuditStatus,
    AuditType,
    BreachNotification,
    # Cases
    Case,
    CaseNote,
    CasePriority,
    CaseStatus,
    CaseTask,
    CaseType,
    ContractStatus,
    Control,
    ControlCategory,
    ControlMapping,
    # Training
    Course,
    CourseStatus,
    CourseType,
    # Customers
    Customer,
    CustomerDocument,
    CustomerReview,
    CustomerRiskRating,
    CustomerStatus,
    CustomerType,
    DocumentType,
    # Evidence
    Evidence,
    EvidenceLink,
    EvidenceReview,
    EvidenceStatus,
    EvidenceType,
    ExceptionStatus,
    FindingSeverity,
    FindingStatus,
    # Frameworks
    Framework,
    FrameworkType,
    # Incidents
    Incident,
    IncidentCategory,
    IncidentResponse,
    IncidentSeverity,
    IncidentStatus,
    IncidentTimeline,
    MappingRelationship,
    MatchDisposition,
    MonitoringRule,
    NotificationStatus,
    PhishingCampaign,
    PhishingResult,
    # Policies
    Policy,
    PolicyAcknowledgement,
    PolicyCategory,
    PolicyException,
    PolicyStatus,
    PolicyVersion,
    QuestionnaireResponse,
    RemediationPlan,
    RemediationStatus,
    ResponseAction,
    ReviewType,
    RuleType,
    SARReport,
    SARStatus,
    ScreeningMatch,
    # Screening
    ScreeningResult,
    ScreeningStatus,
    ScreeningType,
    TaskStatus,
    TrainingAssignment,
    TrainingCompletion,
    # Transactions
    Transaction,
    TransactionAlert,
    TransactionStatus,
    TransactionType,
    # Vendors
    Vendor,
    VendorAssessment,
    VendorContract,
    VendorQuestionnaire,
    VendorStatus,
    VendorTier,
    WatchlistEntity,
    WatchlistSource,
    # Russian Compliance
    RuFrameworkType,
    ProtectionLevel,
    ISPDNCategory,
    ThreatType,
    KIICategory,
    RuDocumentStatus,
    RuDocumentType,
    ResponsibleRole,
    RuTaskPriority,
    RuTaskStatus,
    RuCompanyProfile,
    RuResponsiblePerson,
    RuISPDN,
    RuComplianceDocument,
    RuDocumentTemplate,
    RuComplianceTask,
    RuRequirement,
    RuEmailTemplate,
)
from app.models.constraint import Constraint, ConstraintSeverity, ConstraintType
from app.models.dependency import Dependency, DependencyLayer, RelationshipType
from app.models.entity import Entity, EntityType
from app.models.historical import (
    ConstraintChange,
    DecisionOutcome,
    HistoricalSnapshot,
    TransitionReport,
)
from app.models.risk import RiskLevel, RiskScore
from app.models.risk_justification import RiskJustification
from app.models.scenario import Scenario, ScenarioStatus, ScenarioType

# Phase 2 models
from app.models.scenario_chain import ChainEffect, EffectSeverity, ScenarioChain
from app.models.tenant import Tenant
from app.models.user import User

__all__ = [
    # Base
    "Base",
    "TimestampMixin",
    "TenantMixin",
    # Core models
    "Tenant",
    "User",
    "Entity",
    "EntityType",
    "Constraint",
    "ConstraintType",
    "ConstraintSeverity",
    "Dependency",
    "DependencyLayer",
    "RelationshipType",
    "RiskScore",
    "RiskLevel",
    "Scenario",
    "ScenarioStatus",
    "ScenarioType",
    "AuditLog",
    "AuditAction",
    # Phase 2: Scenario Chains
    "ScenarioChain",
    "ChainEffect",
    "EffectSeverity",
    # Phase 2: Risk Justification
    "RiskJustification",
    # Phase 2: Historical/Institutional Memory
    "HistoricalSnapshot",
    "DecisionOutcome",
    "ConstraintChange",
    "TransitionReport",
    # Phase 2: AI Analysis
    "AIAnalysis",
    "AIAnalysisType",
    "AIAnalysisStatus",
    "AnomalyDetection",
    # Phase 3: Compliance Platform - Frameworks
    "Framework",
    "FrameworkType",
    "Control",
    "ControlCategory",
    "ControlMapping",
    "MappingRelationship",
    "Assessment",
    "AssessmentStatus",
    "AssessmentResult",
    # Phase 3: Compliance Platform - Customers
    "Customer",
    "CustomerType",
    "CustomerStatus",
    "CustomerRiskRating",
    "CustomerDocument",
    "DocumentType",
    "CustomerReview",
    "ReviewType",
    # Phase 3: Compliance Platform - Screening
    "ScreeningResult",
    "ScreeningStatus",
    "ScreeningType",
    "ScreeningMatch",
    "MatchDisposition",
    "WatchlistEntity",
    "WatchlistSource",
    # Phase 3: Compliance Platform - Transactions
    "Transaction",
    "TransactionType",
    "TransactionStatus",
    "TransactionAlert",
    "AlertSeverity",
    "AlertStatus",
    "MonitoringRule",
    "RuleType",
    # Phase 3: Compliance Platform - Policies
    "Policy",
    "PolicyStatus",
    "PolicyCategory",
    "PolicyVersion",
    "PolicyAcknowledgement",
    "PolicyException",
    "ExceptionStatus",
    # Phase 3: Compliance Platform - Evidence
    "Evidence",
    "EvidenceType",
    "EvidenceStatus",
    "EvidenceLink",
    "EvidenceReview",
    # Phase 3: Compliance Platform - Audits
    "Audit",
    "AuditType",
    "AuditStatus",
    "AuditFinding",
    "FindingSeverity",
    "FindingStatus",
    "RemediationPlan",
    "RemediationStatus",
    # Phase 3: Compliance Platform - Vendors
    "Vendor",
    "VendorTier",
    "VendorStatus",
    "VendorAssessment",
    "VendorQuestionnaire",
    "QuestionnaireResponse",
    "VendorContract",
    "ContractStatus",
    # Phase 3: Compliance Platform - Incidents
    "Incident",
    "IncidentSeverity",
    "IncidentStatus",
    "IncidentCategory",
    "IncidentTimeline",
    "IncidentResponse",
    "ResponseAction",
    "BreachNotification",
    "NotificationStatus",
    # Phase 3: Compliance Platform - Training
    "Course",
    "CourseType",
    "CourseStatus",
    "TrainingAssignment",
    "AssignmentStatus",
    "TrainingCompletion",
    "PhishingCampaign",
    "PhishingResult",
    # Phase 3: Compliance Platform - Cases
    "Case",
    "CaseType",
    "CaseStatus",
    "CasePriority",
    "CaseNote",
    "CaseTask",
    "TaskStatus",
    "SARReport",
    "SARStatus",
    # Phase 4: Russian Compliance
    "RuFrameworkType",
    "ProtectionLevel",
    "ISPDNCategory",
    "ThreatType",
    "KIICategory",
    "RuDocumentStatus",
    "RuDocumentType",
    "ResponsibleRole",
    "RuTaskPriority",
    "RuTaskStatus",
    "RuCompanyProfile",
    "RuResponsiblePerson",
    "RuISPDN",
    "RuComplianceDocument",
    "RuDocumentTemplate",
    "RuComplianceTask",
    "RuRequirement",
    "RuEmailTemplate",
]
